### ISSUE TITLE
Add AdvanceTrust

### ISSUE THREAD

**Issue by mdestafadilah** [htr3n/laramod#1]
How i add more plugin in laravel with advancetrust? any tut or direction. thanks.

**Comment by htr3n** [comment]
Hi, do you mean [https://github.com/feripratama/advancetrust](https://github.com/feripratama/advancetrust)? AFAIK, that project defines new commands, providers, facade using Laravel's traditional settings. I have not tried yet, but a potential solution would be create a new module for Advancetrust whilst keep Advancetrust's providers and facades configuration the same way and either (1) customize Advancetrust's commands a bit to generate into the desired module folders or (2) keep Advancetrust's commands in tact and move the outputs of the commands to the right place.
